### ISSUE TITLE
Raised StopIteration on insert

### ISSUE THREAD

**Issue by sdrenn** [xzkostyan/clickhouse-sqlalchemy#27]
When I execute code like this

```db_opt = 'clickhouse://user:password@127.0.0.1/default'
engine = create_engine(db_opt)
Session = sessionmaker(bind=engine)
session = Session()
item = Item(data='test')
session.add(item)
session.flush()
```

the following error appears:
```
RuntimeError: generator raised StopIteration
```
I'm using Python 3.7. On 3.6 it works fine.
Looks like it's because of how Python 3.7 handles StopIteration:
https://www.python.org/dev/peps/pep-0479/

Full error log: [error.log](https://github.com/xzkostyan/clickhouse-sqlalchemy/files/2298740/error.log)

**Comment by xzkostyan** [comment]
Fixed in version 0.0.8.

**Comment by a-rodin** [comment]
It looks like the issues is still here with version 0.0.10 and Python 3.7.3.

**Comment by xzkostyan** [comment]
@a-rodin please provide some example to reproduce this error.

**Comment by a-rodin** [comment]
@xzkostyan I actually encounter the error when I use clickhouse-sqlalchemy with [IPython SQL magic](https://github.com/catherinedevlin/ipython-sql). When I try run magic like

```
%%sql
drop table if exists my_table_to_drop;
```

then it works fine on Python 3.6 (no results returned) and raises a `StopIteration` error on Python 3.7.

It should not be an issue of IPython SQL magic though, because the similar query works fine with SQLite and Python 3.7.
